// 実 Supabase には接続しない。使用する REST 操作だけを PostgreSQL 上で再現する検証用窓口。
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

export const migrationSql = () => readFile(new URL("../supabase/migrations/202609230001_replays.sql", import.meta.url), "utf8");
export const injectedMigrationSql = () => readFile(new URL("../supabase/migrations/202609280001_injected_input.sql", import.meta.url), "utf8");
export const versionMigrationSql = () => readFile(new URL("../supabase/migrations/202609280002_log_version_1_2.sql", import.meta.url), "utf8");
export const readPolicySql = () => readFile(new URL("../supabase/enable-dev-replay-read.sql", import.meta.url), "utf8");

export async function createTestDatabase() {
  const db = new PGlite();
  // ユーザー提示の実テーブル定義と INSERT ポリシー。
  await db.exec(`create role anon; create role authenticated;
    create table public.play_results (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(), version text not null default '1.1',
      session_id uuid not null default gen_random_uuid(), user_id text, device_id text,
      permission text not null, event_key text not null, timestamp timestamptz not null,
      perf double precision not null, delta_ms double precision, event_index integer, sentence_number integer
    );
    alter table public.play_results enable row level security;
    grant usage on schema public to anon;
    grant insert on public.play_results to anon;
    create policy "Allow web test inserts" on public.play_results for insert to anon
      with check (permission = 'web_test');`);
  await db.exec(await migrationSql());
  await db.exec(await injectedMigrationSql());
  await db.exec(await versionMigrationSql());
  await db.exec(await readPolicySql());
  return db;
}

const columns = new Set([
  "id", "created_at", "version", "session_id", "prompt_id", "event_index", "sentence_number",
  "user_id", "device_id", "permission", "event_key", "timestamp", "perf", "delta_ms", "is_injected",
]);
function column(name: string) {
  if (!columns.has(name)) throw new Error(`Unexpected column ${name}`);
  return `"${name}"`;
}

export function createMockRest(db: PGlite, pageCap = 1000) {
  const stats = { reads: 0, writes: 0, lastWrite: [] as Record<string, unknown>[] };
  let failWrites = false;
  const fetchMock: typeof fetch = async (input, init) => {
    const request = new Request(input, init);
    const url = new URL(request.url);
    try {
      if (url.pathname !== "/rest/v1/play_results") return Response.json({ message: "Unknown test route" }, { status: 404 });
      if (request.method === "POST") {
        stats.writes++;
        const rows = await request.json() as Record<string, unknown>[];
        stats.lastWrite = rows;
        if (failWrites) return Response.json({ message: "検証用の通信失敗" }, { status: 503 });
        if (url.searchParams.get("on_conflict") !== "session_id,event_index" ||
          !request.headers.get("prefer")?.includes("resolution=ignore-duplicates")) throw new Error("Unexpected conflict mode");
        const fields = Object.keys(rows[0]);
        const values: unknown[] = [];
        const tuples = rows.map(row => `(${fields.map(field => { values.push(row[field]); return `$${values.length}`; }).join(",")})`);
        await db.transaction(async tx => {
          await tx.exec("set local role anon");
          await tx.query(`insert into play_results (${fields.map(column).join(",")}) values ${tuples.join(",")}
            on conflict (session_id,event_index) do nothing`, values);
        });
        return new Response(null, { status: 201 });
      }
      if (request.method !== "GET") throw new Error("Unexpected HTTP method");
      stats.reads++;
      const fields = url.searchParams.get("select")!.split(",").map(column).join(",");
      const values: unknown[] = [];
      const predicates: string[] = [];
      for (const [name, filter] of url.searchParams) {
        if (["select", "order", "offset", "limit"].includes(name)) continue;
        if (filter.startsWith("eq.")) {
          values.push(filter.slice(3)); predicates.push(`${column(name)} = $${values.length}`);
        } else if (filter.startsWith("in.(") && filter.endsWith(")")) {
          values.push(filter.slice(4, -1).split(",").map(value => value.replace(/^"|"$/g, "")));
          predicates.push(`${column(name)} = any($${values.length}${name === "session_id" ? "::uuid[]" : "::text[]"})`);
        } else throw new Error(`Unexpected test filter ${filter}`);
      }
      const where = predicates.length ? `where ${predicates.join(" and ")}` : "";
      const order = url.searchParams.get("order")!.split(",").map(term => {
        const [name, direction] = term.split(".");
        if (direction !== "asc" && direction !== "desc") throw new Error("Unexpected order");
        return `${column(name)} ${direction}`;
      }).join(",");
      const offset = Number(url.searchParams.get("offset") ?? 0);
      const detailed = !url.searchParams.has("event_key");
      const limit = Math.min(Number(url.searchParams.get("limit") ?? 1000), detailed ? pageCap : 1000);
      if (!Number.isSafeInteger(offset) || !Number.isSafeInteger(limit)) throw new Error("Invalid pagination");
      const { rows, total } = await db.transaction(async tx => {
        await tx.exec("set local role anon");
        const counted = await tx.query<{ count: number }>(`select count(*)::int as count from play_results ${where}`, values);
        const selected = await tx.query(`select ${fields} from play_results ${where} order by ${order} limit ${limit} offset ${offset}`, values);
        return { rows: selected.rows, total: counted.rows[0].count };
      });
      return Response.json(rows, { headers: { "Content-Range": `${rows.length ? `${offset}-${offset + rows.length - 1}` : "*"}/${total}` } });
    } catch (error) {
      const detail = error as { message?: string; code?: string };
      return Response.json({ message: detail.message, code: detail.code }, { status: 400 });
    }
  };
  return { fetch: fetchMock, stats, failWrites: (fail: boolean) => { failWrites = fail; } };
}
